
############Common Part Begin##############################################################################
AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_MAGICONFERENCE_SUPPORT MTK_HAC_SUPPORT CUSTOM_KERNEL_PDR_SENSOR MTK_EMBMS_SUPPORT MTK_SIM_LOCK_POWER_ON_WRITE_PROTECT MTK_CROSSMOUNT_MULTI_CH_SUPPORT MTK_MULTIPLE_TDLS_SUPPORT MTK_MODEM_MONITOR_SUPPORT MTK_BT_BLUEDROID_AVRCP_TG_16 MTK_CROSSMOUNT_SUPPORT CUSTOM_KERNEL_ANSWER_CALL_SENSOR MTK_CAM_STEREO_DENOISE_SUPPORT CUSTOM_KERNEL_UNCALI_MAG_SENSOR CUSTOM_KERNEL_UNCALI_GYRO_SENSOR MTK_BLULIGHT_DEFENDER_SUPPORT MTK_LCM_DEVICE_TREE_SUPPORT MTK_BT_BLUEDROID_A2DP_APTX MTK_NVCONFIG_PARTITION_SUPPORT MTK_BT_BLUEDROID_HFP_AG_17 MTK_AURISYS_PHONE_CALL_SUPPORT MTK_HEADSET_ACTIVE_NOISE_CANCELLATION MTK_DYNAMIC_SBP_SUPPORT MTK_FACTORY_GAMMA_SUPPORT MTK_VT3G324M_SUPPORT MTK_WFC_SUPPORT MTK_BT_BLUEDROID_AVRCP_TG_15 MTK_BT_BLUEDROID_PLUS MTK_CAM_VSDOF_SUPPORT MTK_ECCCI_C2K MTK_EXTERNAL_SIM_SUPPORT MTK_EFUSE_WRITER_SUPPORT MTK_FACTORY_MODE_IN_GB2312 MTK_A1_FEATURE MTK_AUDIO_TUNNELING_SUPPORT CUSTOM_KERNEL_HEART_RATE_SENSOR CUSTOM_KERNEL_SENSORHUB CUSTOM_KERNEL_TILT_DETECTOR_SENSOR CUSTOM_KERNEL_IN_POCKET_SENSOR CUSTOM_KERNEL_WAKE_GESTURE_SENSOR CUSTOM_KERNEL_FACE_DOWN_SENSOR CUSTOM_KERNEL_PICK_UP_SENSOR CUSTOM_KERNEL_GLANCE_GESTURE_SENSOR CUSTOM_KERNEL_PEDOMETER CUSTOM_KERNEL_SHAKE_SENSOR CUSTOM_KERNEL_PEDOMETERENSOR CUSTOM_KERNEL_ACTIVITY_SENSOR CUSTOM_KERNEL_SIGNIFICANT_MOTION_SENSOR CUSTOM_KERNEL_STEP_COUNTER MTK_GMO_ROM_OPTIMIZE MTK_GMO_RAM_OPTIMIZE MTK_ENABLE_MD3 SENSOR_BATCH_SUPPORT MTK_EPDG_SUPPORT MTK_LOSSLESS_BT_SUPPORT MTK_DTAG_DUAL_APN_SUPPORT MTK_DEINTERLACE_SUPPORT MTK_WIFI_MCC_SUPPORT MTK_JEITA_STANDARD_SUPPORT MTK_AUDIO_ALAC_SUPPORT MTK_BQ24261_SUPPORT MTK_REGIONALPHONE_SUPPORT MTK_VIDEO_VP8ENC_SUPPORT LENOVO_X2 MTK_BQ24250_SUPPORT X2_BQ27531_SUPPORT X2_CHARGING_STANDARD_SUPPORT MTK_MAX77819_SUPPORT MTK_PCA9575A_SUPPORT MTK_MD_LOW_BAT_SUPPORT MTK_ALPS_BOX_TVE_SUPPORT MTK_EXTMD_NATIVE_DOWNLOAD_SUPPORT MTK_ALPS_BOX_DONGLE_SUPPORT MTK_ETHERNET_SUPPORT MTK_BESSURROUND_SUPPORT MTK_BOX_AUDIO_DDPLUS_SUPPORT MTK_PLAYBACK_60FPS_TO_30FPS MTK_CAM_MMSDK_SUPPORT MTK_ANT_SUPPORT MTK_MIRAVISION_SETTING_SUPPORT MTK_PUMP_EXPRESS_SUPPORT MTK_BQ24157_SUPPORT MTK_MPEG_DASH_SUPPORT MTK_VOLTE_SUPPORT MTK_IMS_SUPPORT MTK_VOW_SUPPORT MTK_IPTV_SUPPORT MTK_PASSPOINT_R2_SUPPORT MTK_EXTERNAL_DONGLE_SUPPORT MTK_ALPS_BOX_SUPPORT MTK_OD_SUPPORT MTK_BQ24296_SUPPORT MTK_CAM_HDR_SUPPORT MTK_TC1_FEATURE MTK_BATTERY_PROTECT MTK_WIRELESS_CHARGER_SUPPORT MTK_CAM_STEREO_CAMERA_SUPPORT MTK_BESLOUDNESS_SUPPORT MTK_CAM_VHDR_SUPPORT MTK_CAM_EIS_SUPPORT MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT MTK_CAM_FACEBEAUTY_SUPPORT MTK_WFD_SINK_UIBC_SUPPORT MTK_WFD_SINK_SUPPORT MTK_CAM_VSS_SUPPORT MTK_CAM_ZSD_SUPPORT MTK_POWER_EXT_DETECT MTK_CAM_LOMO_SUPPORT MTK_POST_PROCESS_FRAMEWORK_SUPPORT MTK_CAM_DEPTH_AF_SUPPORT MTK_MERGE_INTERFACE_SUPPORT MTK_CAM_NATIVE_PIP_SUPPORT MTK_CAM_NR3D_SUPPORT MTK_CAM_SINGLE_3DSHOT_SUPPORT MTK_CAM_AUTORAMA_SUPPORT MTK_CAM_IMAGE_REFOCUS_SUPPORT MTK_CAM_ASD_SUPPORT MTK_CAM_FD_SUPPORT MTK_MLC_NAND_SUPPORT MTK_FORCE_CLUSTER1 TRUSTONIC_TEE_SUPPORT MTK_RAWFS_NAND_SUPPORT MTK_LOMO_SUPPORT MTK_EXTERNAL_LDO MTK_PMIC_MT6397 MTK_TOUCH_BOOST MTK_SLOW_MOTION_VIDEO_SUPPORT MTK_VIDEO_HEVC_SUPPORT MTK_AUTO_DETECT_ALSPS MTK_GPT_SCHEME_SUPPORT MT6280_SUPER_DONGLE MTK_PRIVACY_PROTECTION_LOCK MTK_SIM_RECOVERY MTK_FAN5402_SUPPORT MTK_AUDIO_HD_REC_SUPPORT MTK_AUDIO MTK_CLEARMOTION_SUPPORT MTK_FSCK_TUNE MTK_NEW_COMBO_EMMC_SUPPORT MTK_PERSIST_PARTITION_SUPPORT MTK_DX_HDCP_SUPPORT MTK_COMBO_NAND_SUPPORT MTK_SMARTBOOK_SUPPORT MTK_DFO_RESOLUTION_SUPPORT MTK_HIGH_RESOLUTION_AUDIO_SUPPORT MTK_AUDIO_EXTCODEC_SUPPORT MTK_SUBTITLE_SUPPORT MTK_SDIOAUTOK_SUPPORT MTK_MSDC1_NOT_SUPPORT_SDR104 MTK_FEMTO_CELL_SUPPORT MTK_CHIPTEST_INT MTK_USER_ROOT_SWITCH MTK_ENABLE_MD5 MTK_WMV_PLAYBACK_SUPPORT MTK_WMA_PLAYBACK_SUPPORT MTK_MOBILE_MANAGEMENT MTK_PARTITION_TABLE_PLAIN_TEXT MTK_DOLBY_DAP_SUPPORT MTK_BQ24156_SUPPORT CUSTOM_KERNEL_BAROMETER MTK_BQ24158_SUPPORT MTK_TABLET_PLUGIN_BUILD MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT MTK_BQ24297_SUPPORT MTK_3GDONGLE_SUPPORT MTK_PM_STATS_SUPPORT MTK_AUDIO_DDPLUS_SUPPORT MTK_SEC_WFD_VIDEO_PATH_SUPPORT MTK_BATLOWV_NO_PANEL_ON_EARLY MTK_SIM_HOT_SWAP_COMMON_SLOT MTK_TER_SERVICE MTK_OWNER_SDCARD_ONLY_SUPPORT MTK_DRM_PLAYREADY_SUPPORT MTK_SHOW_MSENSOR_TOAST_SUPPORT MTK_AUDIO_CHANGE_SUPPORT IS_VCORE_USE_6333VCORE IS_VRF18_USE_6333VRF18 IS_VM_USE_6333VM MTK_VIDEO_AUTO_FLASH_SUPPORT MTK_AIV_SUPPORT MTK_WFD_HDCP_TX_SUPPORT PURE_AP_USE_EXTERNAL_MODEM MTK_NO_NEED_USB_LED MTK_HDMI_HDCP_SUPPORT MTK_INTERNAL_HDMI_SUPPORT MTK_INTERNAL_MHL_SUPPORT MTK_DMNR_TUNING_AT_MD NAND_OTP_SUPPORT MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT MTK_VOIP_ENHANCEMENT_SUPPORT MTK_HANDSFREE_DMNR_SUPPORT MTK_SWCHR_SUPPORT MTK_MT6333_SUPPORT MTK_DRM_KEY_MNG_SUPPORT MTK_SEC_VIDEO_PATH_SUPPORT MTK_WVDRM_L1_SUPPORT MTK_IN_HOUSE_TEE_SUPPORT MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION MTK_CTA_SUPPORT MTK_DFO_SUPPORT MTK_BIP_SCWS MTK_MDM_FUMO MTK_MDM_LAWMO MTK_MDM_SCOMO MTK_UART_USB_SWITCH MTK_AUDIO_RAW_SUPPORT MTK_MD_SHUT_DOWN_NT MTK_CACHE_MERGE_SUPPORT MTK_IPV6_TETHER_PD_MODE MTK_YMAL_SCATTER_FILE_SUPPORT MTK_RADIOOFF_POWER_OFF_MD MTK_MT8193_HDCP_SUPPORT MTK_PLATFORM_OPTIMIZE MTK_HW_ENHANCE MTK_PQ_SUPPORT MTK_AUDIO_ADPCM_SUPPORT HAVE_ADPCMENCODE_FEATURE MTK_2IN1_SPK_SUPPORT MTK_BQ27541_SUPPORT MTK_WFD_SUPPORT MTK_IPV6_TETHER_NDP_MODE MTK_TETHERING_EEM_SUPPORT MTK_AAL_SUPPORT MTK_KERNEL_POWER_OFF_CHARGING MTK_FLIGHT_MODE_POWER_OFF_MD MTK_ENABLE_MD1 MTK_ENABLE_MD2 MTK_ACMT_DEBUG MTK_MMPROFILE_SUPPORT MTK_GPS_SUPPORT MTK_MULTIBRIDGE_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_FM_SUPPORT MTK_TABLET_PLATFORM MTK_AUTO_DETECT_MAGNETOMETER MTK_NCP1851_SUPPORT MTK_NFC_SUPPORT MTK_MASS_STORAGE MTK_COMBO_QUICK_SLEEP_SUPPORT MTK_MT8193_SUPPORT HAVE_AACENCODE_FEATURE MTK_FM_50KHZ_SUPPORT MTK_COMBO_SUPPORT CUSTOM_KERNEL_GYROSCOPE MTK_SHARED_SDCARD MTK_EMMC_DISCARD MTK_DSPIRDBG MTK_MULTI_STORAGE_SUPPORT CUSTOM_KERNEL_ALSPS MTK_ENABLE_VIDEO_EDITOR CUSTOM_KERNEL_ACCELEROMETER MTK_DUAL_MIC_SUPPORT MTK_WAPI_SUPPORT MTK_FD_SUPPORT MTK_DISPLAY_HIGH_RESOLUTION MTK_BT_SUPPORT MTK_TABLET_DRAM MTK_FACEBEAUTY_SUPPORT MTK_FAN5405_SUPPORT MTK_BQ24160_SUPPORT MTK_HIGH_QUALITY_THUMBNAIL MTK_SPH_EHN_CTRL_SUPPORT MTK_FM_TX_SUPPORT MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_BRAZIL_CUSTOMIZATION_CLARO MTK_IPV6_SUPPORT MTK_AUTORAMA_SUPPORT MTK_EAP_SIM_AKA MTK_BSP_PACKAGE MTK_BRAZIL_CUSTOMIZATION MTK_NVRAM_SECURITY CUSTOM_KERNEL_MAGNETOMETER MTK_WLANBT_SINGLEANT MTK_WLAN_SUPPORT MTK_TETHERINGIPV6_SUPPORT MTK_AUTO_DETECT_ACCELEROMETER HAVE_CMMB_FEATURE MTK_MT8193_HDMI_SUPPORT MTK_EMMC_SUPPORT_OTP MTK_TB_APP_CALL_FORCE_SPEAKER_ON MTK_PRODUCT_INFO_SUPPORT MTK_FM_SHORT_ANTENNA_SUPPORT MTK_HDMI_SUPPORT MTK_M4U_SUPPORT MTK_MT8193_NFI_SUPPORT MTK_ION_SUPPORT MTK_FSCK_MSDOS_MTK MTK_BQ24196_SUPPORT MTK_FM_RX_SUPPORT MTK_WB_SPEECH_SUPPORT ENCRY_PARTITION_SUPPORT MTK_SD_REINIT_SUPPORT MTK_SENSOR_SUPPORT MTK_EMMC_SUPPORT MTK_COMBO_CORE_DUMP_SUPPORT MTK_DHCPV6C_WIFI MTK_EMULATOR_SUPPORT MTK_NAND_UBIFS_SUPPORT MTK_YAML_SCATTER_FILE_SUPPORT MTK_VIDEO_VP9_SUPPORT MTK_THERMAL_PA_VIA_ATCMD MTK_FLV_PLAYBACK_SUPPORT MTK_AUDIO_APE_SUPPORT MTK_AVI_PLAYBACK_SUPPORT USE_FRAUNHOFER_AAC MTK_DRM_APP MTK_OGM_PLAYBACK_SUPPORT MTK_MTKPS_PLAYBACK_SUPPORT MTK_MT6306_SUPPORT WIFI_MAC_ADDRESS_RANDOM IMEI_RANDOM YK_LOGO YK_PRODUCT_MODEL YK_PRODUCT_BRAND YK_TARGET_DEVICE YK_PRODUCT_MANUFACTURER YK_CUSTOM_BUILD_VERNO TOUCHPANEL_GESTURE ALSPS_GESTURE SINGLE_DIRECTION_GESTURE LCD_320_480 LCD_480_800 LCD_480_854 LCD_480_960 LCD_540_960 LCD_720_1280 LCD_1080_1960 LCD_720_1440 LCD_640_1280 TOUCHPANEL_TOUCHFELL_IN_PHONE_CALL YKQ_GPS_COCLOCK YKQ_GPS_CLOCK YKQ_BATTERY_PROFILE_FROM_HEADER YKQ_LOW_TEMPERATURE_SHUTDOWN YKQ_USB_OTG_SUPPORT YKQ_CAM_SUB_LENS_SUPPORT YKQ_DUAL_SPEAKER_SUPPORT YKQ_BATTEMP70_THERMAL_SUPPORT YKQ_FRONT_CAM_MCLK1_SUPPORT HX_TEE_ACTIVE_CHECK HX_BOOT_VIBRATE HX_CAMERA_CHAZHI_16M HX_CAMERA_CHAZHI_8M YKQ_SPECIAL_FLASH_MEM_TEST YKQ_FLASH_MEM_TEST_SIMPLIFY YKQ_SPECIAL_FLASH_MEM_TEST_ZWL HX_REMOVE_GOOGLE_VIDEO YKQ_DOUJIA_TEE_SUPPORT YKQ_FINGERPRINT_GESTURE_SUPPORT

AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = MTK_FUSED_LOCATION_SUPPORT MTK_NFC_PACKAGE MTK_CAM_STEREO_CAMERA_FACING MTK_JPEG_HW_RESIZER_TYPE MAXIM_SPEAKER_SUPPORT MTK_VZW_CHIPTEST_MODE_SUPPORT MTK_CAM_ZSDHDR_SUPPORT MTK_CAM_ZSDMFB_SUPPORT MTK_AUDIO_MIC_INVERSE SIM_ME_LOCK_MODE CUSTOM_CONFIG_MAX_DRAM_SIZE MTK_MD_SBP_CUSTOM_VALUE MTK_CAM_MFB_SUPPORT MTK_CAM_CONTINUOUS_SHOT_MODE MTK_VIDEO_4KH264_SUPPORT MTK_HOTKNOT_SUPPORT MTK_TELEPHONY_BOOTUP_MODE_SLOT2 MTK_TELEPHONY_BOOTUP_MODE_SLOT1 MTK_NFC_SE_NUM MTK_OVERLAY_ENGINE_SUPPORT MTK_SIM1_SOCKET_TYPE MTK_SIM2_SOCKET_TYPE CUSTOM_KERNEL_SSW MTK_LCM_PHYSICAL_ROTATION LCM_WIDTH MTK_SINGLE_3DSHOT_SUPPORT MTK_EXTERNAL_MODEM_SLOT MTK_NEON_SUPPORT LCM_HEIGHT MTK_NTFS_OPENSOURCE_SUPPORT YK_EMMC_CAPACITY YKQ_POWERKEY_LONGPRESS_SHUTDOWN HX_XJD_FOTA_DEVICE_DEFINED

AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = CUSTOM_HAL_LENS BOOT_LOGO MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV MTK_PLATFORM CUSTOM_KERNEL_LENS CUSTOM_KERNEL_MAIN_BACKUP_LENS MTK_MODEM_SUPPORT CUSTOM_KERNEL_MAIN_IMGSENSOR MTK_BT_CHIP MTK_WLAN_CHIP CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR CUSTOM_KERNEL_FLASHLIGHT CUSTOM_KERNEL_SUB_IMGSENSOR CUSTOM_KERNEL_SUB_LENS CUSTOM_KERNEL_IMGSENSOR MTK_FM_RX_AUDIO MTK_COMBO_CHIP MTK_GPS_CHIP CUSTOM_KERNEL_SUB_BACKUP_LENS CUSTOM_KERNEL_MAIN_LENS MTK_FM_TX_AUDIO MTK_FM_CHIP CUSTOM_KERNEL_MAIN2_IMGSENSOR BOOT_LOGO CUSTOM_LK_LCM CUSTOM_KERNEL_LCM CUSTOM_KERNEL_TOUCHPANEL YK_CUSTOM_KERNEL_ACCELEROMETER YK_CUSTOM_KERNEL_ALSPS YK_CUSTOM_KERNEL_MAGNETOMETER YK_CUSTOM_KERNEL_GYROSCOPE CUSTOM_KERNEL_FASTCHARGING CUSTOM_KERNEL_TYPE_C_SUPPORT CUSTOM_KERNEL_FINGERPRINT YK_CUSTOM_KERNEL_INFRARED YK_CUSTOM_KERNEL_DTV YK_PLATFORM_CONFIG YK_BOARD_CONFIG YK_CUSTOMER_CONFIG YK_AUDIO_PA_MODE LCD_RESOLUTION YKQ_DOUJIA_TEEI_SOURCE

##LCD resolution:
LCD_320_480 = no
LCD_480_800 = no
LCD_480_854 = no
LCD_480_960 = no
LCD_540_960 = no
LCD_640_1280 = no
LCD_720_1280 = no
LCD_720_1440 = no
LCD_1080_1960 = no

##TP simulate PS:
TOUCHPANEL_TOUCHFELL_IN_PHONE_CALL = no

##TP Gesture:
TOUCHPANEL_GESTURE = no
#package name 
HX_SMARTWAKE_C_ENTRY = no
HX_SMARTWAKE_E_ENTRY = no
HX_SMARTWAKE_M_ENTRY = no
HX_SMARTWAKE_O_ENTRY = no
HX_SMARTWAKE_S_ENTRY = no
HX_SMARTWAKE_V_ENTRY = no
HX_SMARTWAKE_W_ENTRY = no
HX_SMARTWAKE_Z_ENTRY = no
#actvity name
HX_SMARTWAKE_C_ACTIVTITY = no
HX_SMARTWAKE_E_ACTIVTITY = no
HX_SMARTWAKE_M_ACTIVTITY = no
HX_SMARTWAKE_O_ACTIVTITY = no
HX_SMARTWAKE_S_ACTIVTITY = no
HX_SMARTWAKE_V_ACTIVTITY = no
HX_SMARTWAKE_W_ACTIVTITY = no
HX_SMARTWAKE_Z_ACTIVTITY = no

##PS gesture:
ALSPS_GESTURE = no
SINGLE_DIRECTION_GESTURE = no

##sub lens:
YKQ_CAM_SUB_LENS_SUPPORT = no

##GPS Clock:
YKQ_GPS_CLOCK = no

##OTG function
YKQ_USB_OTG_SUPPORT = no

##Battery profile:
YKQ_BATTERY_PROFILE_FROM_HEADER = yes
YKQ_LOW_TEMPERATURE_SHUTDOWN = no

HX_FACTORYTEST_MENU_BAR_TEST = yes

##yangkun add gsensor test in FACTORYTEST 2017/12/08
HX_FACTORYTEST_GSENSOR_GRAPHIC = yes
## add end

##longpress powerkey leads to hardware shutdown or reset system.
##Notice: 
## 0:function close; 1: 5s; 2:8s; 3:11s; 4 14s  
YKQ_POWERKEY_LONGPRESS_SHUTDOWN = 0

##Thermal policy:when bat-temp increase to 70 degree,system reset,else default 60 degree
YKQ_BATTEMP70_THERMAL_SUPPORT = no

HX_REMOVE_POWER_ON_SOUND = no
HX_REMOVE_BOOT_ANIMATION = no
##cjg add
HX_DOUBLE_CAMERA_BLOCKED = yes
##add end

##TEE related:
YKQ_DOUJIA_TEE_SUPPORT = no
YKQ_FINGERPRINT_GESTURE_SUPPORT = no
YKQ_DOUJIA_TEEI_SOURCE = 

## yangkun add FactoryTest start 2018/03/16
FACTORYTEST_STORE_WITH_NV = yes
HX_FACTORYTEST_SAVE_ALL_STATUS = yes
TOUCHPANEL_TOUCHFELL_IN_PHONE_CALL = no
HX_FACTORYTEST_OTG = no
HX_FACTORYTEST_LCDTEST_WITH_WHITE_BLACK_COLOR = yes
HX_SUB_FLASHLIGHT_SUPPORT = no
YK_HUALING_BREATH_LED = no
HX_FACTORYTEST_BATTERY = yes
FACTORYTEST_HIDE_MENUKEY = no
FACTORYTEST_HIDE_BACKKEY = no
FACTORYTEST_HIDE_HOMEKEY = no
FACTORYTEST_LCDTESTCLICK = no
HX_EXISTENCE_TWO_MIC = no
HX_FACTORYTEST_GSENSOR_GRAPHIC = yes
HX_FACTORYTEST_SAVE_TO_BARCODE = yes
HX_FACTORY_SHOW_CHIP_INFO = no
HX_FACTORYTEST_SYSTEM_FRONT_CAMERA = no
HX_FACTORYTEST_SYSTEM_BACK_CAMERA = no
HX_FACTORYTEST_TP_VERSION = no
HX_FACTORYTEST_MENU_KEY_TEST = yes
## add end

#swallow add
#\D2Ƴ\FD\B9\D8\D3\DA\CAֻ\FA\C0\EF\C3\E6\B5\C4logoͼƬ\A3\ACĬ\C8\CFlogoͼƬ\B2\BB\CF\D4ʾ
HX_REMOVE_ABOUT_LOGO = yes
#swallow end


#qyl addneed emeragency call log
NEED_EMERGENCY_CALL_LOG = no
#qyl end
#pingyh add start
HX_TEE_ACTIVE_CHECK = no
#pingyh end

# hefang add for custom
YK736_XINJIDE_G1_EU_UI = no
YK736_XINJIDE_G1_US_UI = no
HX_BOOT_VIBRATE = no
HX_TIME_DISPLAY_AM_PM = yes

## yangkun add AgeTest 2018/03/22
HX_AGETEST_APP = no
## add end
## yangkun add for Cycle AgeTest start 2018/03/22
HX_AGETEST_CYCLE = no
HX_AGETEST_VIBRATE_TEST = no
HX_AGETEST_NO_HEADSET_TEST = no
HX_AGETEST_FLAG = no
## add end


#swallow add
#状态栏运营商信息添加网络类型
HX_CARRIER_NETWORK_TYPE = no
##数据流量为关时，信号强度上显示X
HX_DATA_DISABLED_ICON = no
##信号强度上显示！
HX_HIDE_SIM_EXMARK = no
#数据流量开时显示上下箭头和网络类型
YKQ_SHOW_DATAINOUT = no
HX_SHOU_DATA_OUTIN_POS = no
#闹钟中alarm需要从周一开始
HX_ALARM_DAY_ORDER = no
#添加一键清理图标
HX_ONE_KEY_CLEAR_SUPPORT = no
#设置/网络和互联网/流量使用情况，查看卡1和卡2的移动数据都为开启状态
HX_DEF_DATA_SIM = no
#动态显示stk名称
HX_STKNAME_DYNAMIC = no
#移除Google原生wifi热点状态栏图标
HX_REMOVE_GOOGLE_HOTSPOT_ICON = yes
#通话记录显示紧急号码
HX_SHOW_EMERGENCY_NUMBER = no
HX_EMERGENCY_NUMBER_911 = no
HX_EMERGENCY_NUMBER_911_112 = no
#swallow end
##add by wangyan
HX_REMOVE_DATA_CONTROL = no
##end
############Common Part End#######################################################################################


###customized requirement begin###################################################################################

##Start of YK736_EMMC_YKQ_FWVGA#####FWVGA:480X854, YKQ#######
##LCM:
LCM_HEIGHT = 854
LCM_WIDTH = 480
BOOT_LOGO=fwvga
LCD_480_854 = yes
LCD_RESOLUTION = LCM_480_854
CUSTOM_LK_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
# ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
 #ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx

YKQ_FACTORY_SHOW_SUPPORT = yes 

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc2145_mipi_yuv gc0310_mipi_yuv
CUSTOM_HAL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_HAL_SUB_IMGSENSOR = gc0310_mipi_yuv
CUSTOM_KERNEL_IMGSENSOR = gc2145_mipi_yuv gc0310_mipi_yuv
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_KERNEL_SUB_IMGSENSOR = gc0310_mipi_yuv

CUSTOM_HAL_LENS = dummy_lens
CUSTOM_HAL_MAIN_LENS = dummy_lens
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = dummy_lens
CUSTOM_KERNEL_MAIN_LENS = dummy_lens
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = bGT_Hotknot

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER = 

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new 

##fingerprint:
#CUSTOM_KERNEL_FINGERPRINT = cs2511 ft9338
#CUSTOM_KERNEL_FINGERPRINT = ft9338
CUSTOM_KERNEL_FINGERPRINT = icn7152l
#CUSTOM_FILES_BRAND = zwl_common


##MODEM:6M
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
##CT6M
#CUSTOM_MODEM=yk736_v01_lwctg_gsm-triple_wcdma-b1b8_fdd-b1b3b5_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
##Open-market 6M:
CUSTOM_MODEM=yk736_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
YK_EMMC_CAPACITY=12808

##MODEM:4M
#MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
#YK_EMMC_CAPACITY=12816

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b4b5_fdd-b2b4b5b7b12b17
YK_EMMC_CAPACITY=12808


#PSC5425_CHARGER_SUPPORT
YK_CUSTOMER_CONFIG = YK736_CUSTOMER_YKQ_FWVGA

#YK_BOARD_CONFIG=YK736_CONFIG YK736_V10_CONFIG
#YK_EMMC_CAPACITY=12808_DIS
#YK_CUSTOMER_CONFIG = YK736_CUSTOMER_YKQ_FWVGA EMMC_DISABLE_HS400_SPEED

YK_CUSTOM_BUILD_VERNO = YKQ_YK736_M02-Y12_GS_ALS_FP_GPSCO_39GO_LWG_12808_20180302_1414

##End of YK736_EMMC_YKQ_FWVGA#################################

##Start of YK736_EMMC_YKQ_HD640_CT6M#####HD640:640X1280, YKQ#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 640
BOOT_LOGO=hd640
LCD_640_1280 = yes
LCD_RESOLUTION = LCM_640_1280
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw hi846_mipi_raw hi556f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw hi846_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = icn87xx ft6x36 GT1X
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
#TOUCHPANEL_GESTURE = yes
#CUSTOM_KERNEL_TOUCHPANEL = GT1X ilitek
#CUSTOM_KERNEL_TOUCHPANEL = icn87xx

##magnetometer
#CUSTOM_KERNEL_MAGNETOMETER = no
#YK_CUSTOM_KERNEL_MAGNETOMETER = 

##accelerometer:
#CUSTOM_KERNEL_ACCELEROMETER = yes
#YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new
#YK_CUSTOM_KERNEL_ACCELEROMETER = lsm6ds3_acc_new

##gyroscope:
#CUSTOM_KERNEL_GYROSCOPE = no
#YK_CUSTOM_KERNEL_GYROSCOPE = lsm6ds3gy_new

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new epl259x_new
#CUSTOM_KERNEL_ALSPS = no
#YK_CUSTOM_KERNEL_ALSPS =

##fingerprint:
#CUSTOM_KERNEL_FINGERPRINT = cs2511 ft9338
#CUSTOM_KERNEL_FINGERPRINT = ft9338
#CUSTOM_KERNEL_FINGERPRINT = cs2511

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:xen
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
##CT6M:
CUSTOM_MODEM=yk736_v01_lwctg_gsm-triple_wcdma-b1b8_fdd-b1b3b5_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
##Open-market 6M:
#CUSTOM_MODEM=yk736_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3_tdd-b38b39b40b41_tds-b34b39_evdo-bc0

YK_EMMC_CAPACITY=6408DDR3
#YK_EMMC_CAPACITY=12808

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_YKQ_HD640

MTK_CT4GREG_APP = yes
MTK_DEVREG_APP = yes

##End of YK736_EMMC_YKQ_HD640_CT6M#################################


##Start of YK736_EMMC_YKQ_FWVGA_PLUS_CT6M#####FW+:480X960, YKQ#######
##LCM:
LCM_HEIGHT = 960
LCM_WIDTH = 480
BOOT_LOGO=fwplus
LCD_480_960 = yes
LCD_RESOLUTION = LCM_480_960
CUSTOM_LK_LCM = st7701s_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7701s_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = icn87xx ft6x36 GT1X
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
#CUSTOM_KERNEL_TOUCHPANEL = icn87xx

##magnetometer
#CUSTOM_KERNEL_MAGNETOMETER = no
#YK_CUSTOM_KERNEL_MAGNETOMETER = 

##accelerometer:
#CUSTOM_KERNEL_ACCELEROMETER = no
#YK_CUSTOM_KERNEL_ACCELEROMETER = 

##gyroscope:
#CUSTOM_KERNEL_GYROSCOPE = no
#YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new
#YK_CUSTOM_KERNEL_ALSPS = epl259x_new
#YK_CUSTOM_KERNEL_ALSPS = cm36558
#CUSTOM_KERNEL_ALSPS = no
#YK_CUSTOM_KERNEL_ALSPS =

##fingerprint:
#CUSTOM_KERNEL_FINGERPRINT = cs2511 ft9338
#CUSTOM_KERNEL_FINGERPRINT = ft9338
#CUSTOM_KERNEL_FINGERPRINT = cs2511

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:xen
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
CUSTOM_MODEM=yk736_v01_lwctg_gsm-triple_wcdma-b1b8_fdd-b1b3b5_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
#CUSTOM_MODEM=yk736_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3b5_tdd-b38b39b40b41_tds-b34b39_evdo-bc0

YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_YKQ_FWVGA_PLUS

MTK_CT4GREG_APP = yes
MTK_DEVREG_APP = yes

##End of YK736_EMMC_YKQ_FWVGA_PLUS_CT6M######################################

##Start of YK736_EMMC_CAIFU9_KS937_HDPLUS#####HD-PLUS:720X1440, CAIFU9-KS937#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx ili9881d_6735_dsi_yk6xx otm1290a_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx ili9881d_6735_dsi_yk6xx otm1290a_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = hi556f_mipi_raw s5k3l8_mipi_raw ar1335_mipi_raw gc13023_mipi_raw gc5025f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = s5k3l8_mipi_raw ar1335_mipi_raw gc13023_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = hi556f_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = hi556f_mipi_raw s5k3l8_mipi_raw ar1335_mipi_raw gc13023_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = s5k3l8_mipi_raw ar1335_mipi_raw gc13023_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = hi556f_mipi_raw gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X ilitek
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

##Fingerprint:
CUSTOM_KERNEL_FINGERPRINT = chipsailing2511_tee icn7xxx_tee

##DOUJIA-TEE:
MICROTRUST_TEE_SUPPORT = yes
MTK_TEE_SUPPORT = yes
YKQ_DOUJIA_TEE_SUPPORT = yes
YKQ_FINGERPRINT_GESTURE_SUPPORT = yes
YKQ_DOUJIA_TEEI_SOURCE = YK736_CAIFU_KS937

##FullScreen:
MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##single SIM:
MTK_MULTI_SIM_SUPPORT = ss
MTK_MULTIPLE_IMS_SUPPORT = 1

##GPS clock
YKQ_GPS_CLOCK=yes

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40


YK_EMMC_CAPACITY=12816

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS937_HDPLUS HIGH_BATTERY_VOLTAGE_SUPPORT CAIFU_HELITAI_S5K3L8_OTP AR1335_SENSOR_OTP YKQ_DISABLE_CHARGING_TIMEOUT VOLUP_KEY_TO_BACK
##Start of YK736_EMMC_CAIFU9_KS937_HDPLUS_PRIVATE#############
##Start of YK736_EMMC_CAIFU9_KS937_HDPLUS_SA_MTN#############

#GMS config 
#BUILD_AGO_GMS = yes
BUILD_GMS = yes
BUILD_GMS_VERSION = GMS8.1_201803
MTK_SIGNATURE_CUSTOMIZATION = yes
#GMS end

#VOLTE OFF
MTK_VOLTE_SUPPORT = no
MTK_VILTE_SUPPORT = no
MTK_IMS_SUPPORT = no
MTK_WFC_SUPPORT = no
MTK_DYNAMIC_SBP_SUPPORT = no

WW_BOOT_LOGO = hdplus_hisense
CUSTOM_FILES_BRAND = fcl_yk736_cf9_937a_hisense_mtn
RESOURCE_OVERLAY = fcl_yk736_cf9_937a_hisense_mtn

YK_PRODUCT_MODEL = KS937A
YK_PRODUCT_BRAND = Hisense
YK_PRODUCT_NAME = KS937A
YK_TARGET_DEVICE = HS6739MT
YK_PRODUCT_BOARD = Hisense
YK_PRODUCT_MANUFACTURER = Hisense
YK_PRODUCT_USB = KS937A

YK736_CAIFU_KS937A_MTN_UI = yes
WW_CF9_HISENSE_CP_AUDIO = yes
#HX_SHUT_ANIM = yes
#WW_SHUT_ANIMATION = yes
#WW_SHUT_ANIMATION_TIME = 4
HX_CAMERA_CHAZHI_16M = yes
HX_CAMERA_CHAZHI_8M = yes


## yangkun add AgeTest 2018/03/22
HX_AGETEST_APP = yes
## add end

HX_DATA_DISABLED_ICON = yes
HX_BOOT_VIBRATE = yes
HX_TIME_DISPLAY_AM_PM = yes
HX_SETTING_VIBRATE_FOR_INCALL_DEFAULT_OPEN = yes
HX_BRIGHTNESS_PERCENT_80 = yes
HX_SCREEN_OFF_TIME_30S = yes
HX_BOOT_SCREEN_HALF_BLACK = yes
LAUNCHER_APPS_BG_TRANSPARENCY = yes
LAUNCHER_FIXED_WALLPAPER = yes

YK_CUSTOM_BUILD_VERNO = YK736_CAIFU9_KS937A_MTN_V01_20180426
##End of YK736_EMMC_CAIFU9_KS937_HDPLUS_SA_MTN##############################
##End of YK736_EMMC_CAIFU9_KS937_HDPLUS_PRIVATE##############################
##End of YK736_EMMC_CAIFU9_KS937_HDPLUS#####################################################


##Start of YK736_EMMC_CAIFU9_KS927_HD640#####HD640:640X1280, CAIFU9-KS927#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 640
BOOT_LOGO=hd640
LCD_640_1280 = yes
LCD_RESOLUTION = LCM_640_1280
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
YKQ_GPS_CLOCK=yes

#12816
#YK_EMMC_CAPACITY=12816
YK_EMMC_CAPACITY=12816_12808_CAIFU9

YKQ_BATTERY_PROFILE_FROM_HEADER = yes
YKQ_LOW_TEMPERATURE_SHUTDOWN = yes

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS927_HD640 HIGH_BATTERY_VOLTAGE_SUPPORT YKQ_DISABLE_CHARGING_TIMEOUT VOLUP_KEY_TO_BACK
#YK736_CUSTOMER_CAIFU9_KS927_HD640_OBJ

##End of YK736_EMMC_CAIFU9_KS927_HD640#################################


##Start of YK736_EMMC_CAIFU9_KS927_HDPLUS#####HDPLUS:720X1440, CAIFU9-KS927#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8034_mipi_raw gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8034_mipi_raw gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8034_mipi_raw gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8034_mipi_raw gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = dw9714af fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = dw9714af fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = dw9714af fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = dw9714af fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
YKQ_GPS_CLOCK=yes

#12816
#YK_EMMC_CAPACITY=12816
YK_EMMC_CAPACITY=12816_12808_CAIFU9
#YK_EMMC_CAPACITY=25624

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS927_HDPLUS HIGH_BATTERY_VOLTAGE_SUPPORT YKQ_DISABLE_CHARGING_TIMEOUT DW9763_LENS_SUPPORT VOLUP_KEY_TO_BACK
# GTP_FW_AUTO_UPDATE

##Start of YK736_EMMC_CAIFU9_KS927_HDPLUS_PRIVATE##
##Start of YK736_EMMC_CAIFU9_KS927_HDPLUS_Hisense_F27_4G##
#CUSTOM_FILES_COMMON = wl_common
CUSTOM_FILES_BRAND = wl_yk736_cf9_927_hd6_hisense
RESOURCE_OVERLAY = wl_yk736_cf9_927_hd6_hisense

#GMS config 
BUILD_GMS = yes
BUILD_GMS_VERSION = GMS8.1_r3
#GMS end

YK736_CF9_927_HD6_HISENSE = yes
WW_CF9_HISENSE_CP_AUDIO = yes
YK736_CF9_927_HISENSE_F17_UI = yes
#HX_PREINSTALL_APKS_KS927 = yes
WW_BOOT_LOGO = hdplus_hisense
YK_PRODUCT_MODEL = Hisense Infinity F17
YK_PRODUCT_BRAND = Hisense
YK_TARGET_DEVICE = HS6739MT
YK_PRODUCT_NAME  = F17_4G
YK_PRODUCT_MANUFACTURER = Hisense
YK_PRODUCT_USB = Hisense
YK_PRODUCT_BOARD = Hisense

MTK_SECURITY_BOOT_SUPPORT=yes

YK_CUSTOM_BUILD_INTERNAL_VERSION = YK736_CAIFU9_KS927_HISENSE_INFINITY_F17_HDPLUS_V01_20180208
YK_CUSTOM_BUILD_VERNO = Hisense_F17_4G_00_S01_20180208
##End of YK736_EMMC_CAIFU9_KS927_HDPLUS_Hisense_F27_4G##
##End of YK736_EMMC_CAIFU9_KS927_HDPLUS_PRIVATE##
##End of YK736_EMMC_CAIFU9_KS927_HDPLUS#################################


##Start of YK736_EMMC_CAIFU9_KS907E_HDPLUS#####HDPLUS:720X1440, CAIFU9-KS907E#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw gc13023_mipi_raw 
CUSTOM_HAL_MAIN_IMGSENSOR = ar1335_mipi_raw s5k3l8_mipi_raw gc13023_mipi_raw 
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw ar1335_mipi_raw s5k3l8_mipi_raw gc13023_mipi_raw 
CUSTOM_KERNEL_MAIN_IMGSENSOR = ar1335_mipi_raw s5k3l8_mipi_raw gc13023_mipi_raw 
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

##FingerPrint:
CUSTOM_KERNEL_FINGERPRINT = chipsailing2511_tee icn7xxx_tee

##DOUJIA-TEE:
MICROTRUST_TEE_SUPPORT = yes
MTK_TEE_SUPPORT = yes
YKQ_DOUJIA_TEE_SUPPORT = yes
YKQ_FINGERPRINT_GESTURE_SUPPORT = yes
YKQ_DOUJIA_TEEI_SOURCE = YK736_CAIFU_KS937

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12_caifu_ks907_ant
YKQ_GPS_CLOCK=yes

#12816
YK_EMMC_CAPACITY=12816
#YK_EMMC_CAPACITY=12816_12808_CAIFU9

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS927_HDPLUS YK736_CUSTOMER_CAIFU9_KS907_HDPLUS HIGH_BATTERY_VOLTAGE_SUPPORT YKQ_DISABLE_CHARGING_TIMEOUT VOLUP_KEY_TO_BACK CAIFU_HELITAI_S5K3L8_OTP AR1335_SENSOR_OTP
##############################################
##############################################
##############################################
CUSTOM_FILES_BRAND=hf_yk736_caifu9_ks927b_hdplus
BOOT_LOGO=hx_hdplus
HX_REMOVE_POWER_ON_SOUND = yes
#HX_REMOVE_BOOT_ANIMATION = no

YK_PRODUCT_MODEL = WS55L
YK_PRODUCT_BRAND = WHOOP
YK_PRODUCT_NAME = WS55L
YK_TARGET_DEVICE = WS55L
YK_PRODUCT_BOARD = WS55L

#GMS config 
BUILD_GMS = yes
BUILD_GMS_VERSION = GMS8.1_r3
#GMS end

YK_CUSTOM_BUILD_VERNO = WHOOP_WS55L_V01
##End of YK736_EMMC_CAIFU9_KS907E_HDPLUS#################################


##Start of YK736_EMMC_CAIFU9_KS907_HD640#####HD640:640X1280, CAIFU9-KS907#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 640
BOOT_LOGO=hd640
LCD_640_1280 = yes
LCD_RESOLUTION = LCM_640_1280
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = cs2511

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12_caifu_ks907_ant
YKQ_GPS_CLOCK=yes

#12808
YK_EMMC_CAPACITY=12808
YK_EMMC_CAPACITY=12816

YKQ_BATTERY_PROFILE_FROM_HEADER = yes
YKQ_LOW_TEMPERATURE_SHUTDOWN = yes

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS927_HD640 HIGH_BATTERY_VOLTAGE_SUPPORT YKQ_DISABLE_CHARGING_TIMEOUT VOLUP_KEY_TO_BACK

##End of YK736_EMMC_CAIFU9_KS907_HD640#################################


##Start of YK736_EMMC_CAIFU9_KS907_HDPLUS#####HDPLUS:720X1440, CAIFU9-KS907#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw hi556f_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw hi846_mipi_raw ar1335_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X msg2xxx_v3a00
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = cs2511

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
#MTK_MD1_SUPPORT = 14
#MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
#MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12_caifu_ks907_ant

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
YKQ_GPS_CLOCK=yes

#12816
#YK_EMMC_CAPACITY=12808
YK_EMMC_CAPACITY=12816_12808_CAIFU9

YKQ_BATTERY_PROFILE_FROM_HEADER = yes
YKQ_LOW_TEMPERATURE_SHUTDOWN = yes

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_CAIFU9_KS927_HDPLUS HIGH_BATTERY_VOLTAGE_SUPPORT YKQ_DISABLE_CHARGING_TIMEOUT YK736_CUSTOMER_CAIFU9_KS907_HDPLUS VOLUP_KEY_TO_BACK


##Start of YK736_EMMC_CAIFU9_KS907_HDPLUS_PRIVATE##
##Start of YK736_EMMC_CAIFU9_KS907_HDPLUS_Hisense_F17##
##MODEM:4M
MTK_MD1_SUPPORT = 9
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
YKQ_GPS_CLOCK=yes
CUSTOM_FILES_BRAND = wl_yk736_cf9_927_hd6_hisense
RESOURCE_OVERLAY = wl_yk736_cf9_907b_hisense
#GMS config 
BUILD_GMS = yes
BUILD_GMS_VERSION = GMS8.1_r3
#GMS end
YK736_CF9_927_HD6_HISENSE = yes
YK736_CF9_927_HISENSE_F17_PRO_UI = yes
WW_CF9_HISENSE_CP_AUDIO = yes

YK_PRODUCT_MODEL = Hisense F17 Pro
YK_PRODUCT_BRAND = Hisense
YK_TARGET_DEVICE = HS6739MT
YK_PRODUCT_NAME  = F17_4G_20
YK_PRODUCT_MANUFACTURER = Hisense
YK_PRODUCT_USB = Hisense
YK_PRODUCT_BOARD = Hisense

##TEE Begin ##
CUSTOM_KERNEL_FINGERPRINT = chipsailing2511_tee
MICROTRUST_TEE_SUPPORT = yes
MTK_TEE_SUPPORT = yes
YK_CUSTOM_BUILD_INTERNAL_VERSION = YK736_CAIFU9_KS907B_HISENSE_INFINITY_F17_PLUS_HDPLUS_V01_20180306_TEE
YK_CUSTOM_BUILD_VERNO = Hisense_F17_4G_20_S01_20180306
##TEE End ##
##End of YK736_EMMC_CAIFU9_KS907_HDPLUS_Hisense_F17##

##Begin of YK736_EMMC_CAIFU9_KS907_HDPLUS_Hisense_ATT##
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b4b5_fdd-b2b3b4b5b7b12_caifu_ks907_ant_ATT_UNEFON_simlock
CUSTOM_FILES_BRAND = wl_yk736_cf9_907_hisense_att

#GMS config 
BUILD_AGO_GMS = yes
BUILD_GMS_VERSION = GMS8.1_go_R1
#GMS end

RESOURCE_OVERLAY = wl_yk736_cf9_907_hisense_att
WW_BOOT_LOGO = hdplus_att
YK736_CF9_HISENSE_ATT_UI = yes
YK736_CF9_927_HD6_HISENSE = yes
WW_CF9_HISENSE_CP_AUDIO_ATT  = yes
HX_FLASHLIGHT_LOW_BATTERY = yes
WW_TIMEZONE = America/Mexico_City
WW_SHUT_ANIMATION = yes
WW_SHUT_ANIMATION_TIME = 7
YK_CUSTOM_BUILD_INTERNAL_VERSION = YK736_CAIFU9_KS907A_HISENSE_F23_PLUS_HDPLUS_V01_20180306_TEE
YK_CUSTOM_BUILD_VERNO = Hisense_F17_4G_10_S01_20180306
##End of YK736_EMMC_CAIFU9_KS907_HDPLUS_Hisense_ATT##
##End of YK736_EMMC_CAIFU9_KS907_HDPLUS_PRIVATE##
##End of YK736_EMMC_CAIFU9_KS907_HDPLUS#################################


##Start of YK736_EMMC_YIZHANTONG_L5501_HD640#####HD640:640X1280, YIZHANTONG-L5501#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 640
BOOT_LOGO=hd640
LCD_640_1280 = yes
LCD_RESOLUTION = LCM_640_1280
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc5025_mipi_raw gc033a_mipi_raw gc0310_mipi_yuv
CUSTOM_HAL_MAIN_IMGSENSOR = gc5025_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc033a_mipi_raw gc0310_mipi_yuv
CUSTOM_KERNEL_IMGSENSOR = gc5025_mipi_raw gc033a_mipi_raw gc0310_mipi_yuv
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc5025_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc033a_mipi_raw gc0310_mipi_yuv

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
##Europe Version:
#MTK_MD1_SUPPORT = 14
#MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
#MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20

##American Version:
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b2b5_fdd-b2b4b5b7b17

##MemeoryCfg:
YK_EMMC_CAPACITY=12816

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_YIZHANTONG_L5501_HD640

##End of YK736_EMMC_YIZHANTONG_L5501_HD640#################################


##Start of YK736_EMMC_XINDIHENG_M130_HD720#####HD720:720X1280, XINDIHENG-M130#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 720
BOOT_LOGO=hd720
LCD_720_1280 = yes
LCD_RESOLUTION = LCM_720_1280
CUSTOM_LK_LCM = nt35523_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = nt35523_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = a5142_mipi_raw gc2385_mipi_raw gc2385f_mipi_raw gc030a_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = a5142_mipi_raw gc2385_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc2385f_mipi_raw gc030a_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = a5142_mipi_raw gc2385_mipi_raw gc2385f_mipi_raw gc030a_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = a5142_mipi_raw gc2385_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc2385f_mipi_raw gc030a_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = icn7152l

##MODEM:6M
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
MTK_PROTOCOL2_RAT_CONFIG = L/W/G
CUSTOM_MODEM=yk736_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3_tdd-b38b39b40b41_tds-b34b39_evdo-bc0

YK_EMMC_CAPACITY=12808

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_XINDIHENG_M130_HD720 HIGH_BATTERY_VOLTAGE_SUPPORT

##End of YK736_EMMC_XINDIHENG_M130_HD720#################################


##Start of YK736_EMMC_FULING_E727_HD720#####HD720:720X1280, FULING-E727#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 720
BOOT_LOGO=hd720
LCD_720_1280 = yes
LCD_RESOLUTION = LCM_720_1280
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx nt35523_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx nt35523_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw gc2385f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

#CUSTOM_KERNEL_ALSPS = no
YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

##Longpress Powerkey Shutdown system:
YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

##modem 4m:
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b5b8_fdd-b2b4b5b7b17b40

#12816
YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_FULING_E727_HD720 HIGH_BATTERY_4_4_V SUB_FLASHLIGHT_SUPPORT YK_TP_TRADE_BACK_MENU
##############################################
##############################################
##############################################
CUSTOM_FILES_BRAND=hf_yk736_fuling_e727_hd720
BOOT_LOGO=hx_hd720
HX_REMOVE_POWER_ON_SOUND = yes
#HX_REMOVE_BOOT_ANIMATION = no

YK_PRODUCT_MODEL = E727
YK_PRODUCT_BRAND = Karbonn
YK_PRODUCT_NAME = E727
YK_TARGET_DEVICE = E727
YK_PRODUCT_BOARD = E727

#GMS config 
BUILD_AGO_GMS = yes
BUILD_GMS_VERSION = GMS8.1_go_R1
#GMS end

YK_CUSTOM_BUILD_VERNO = Karbonn_E727_V01
##End of YK736_EMMC_FULING_E727_HD720#################################

##Start of YK736_EMMC_FULING_E729_HD640#####HD640:640X1280, FULING-E729#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 640
BOOT_LOGO=hd640
LCD_640_1280 = yes
LCD_RESOLUTION = LCM_640_1280
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx

#LCM_HEIGHT = 960
#LCM_WIDTH = 480
#BOOT_LOGO=fwplus
#LCD_480_960 = yes
#LCD_RESOLUTION = LCM_480_960
#CUSTOM_LK_LCM = st7701s_6735_dsi_yk6xx
#CUSTOM_KERNEL_LCM = st7701s_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8034_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8034_mipi_raw gc5025_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8034_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw gc2385f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8034_mipi_raw gc5025_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw gc2385f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT=sunwavecorp

##Longpress Powerkey Shutdown system:
YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##modem 4m:
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b5b8_fdd-b2b4b5b7b17b40

#12816
YK_EMMC_CAPACITY=6408DDR3
#YK_EMMC_CAPACITY=12816

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_FULING_E729_HD640 HIGH_BATTERY_4_4_V SUB_FLASHLIGHT_SUPPORT

##End of YK736_EMMC_FULING_E729_HD640#################################


##Start of YK736_EMMC_KUANGRE_A17_FWVGA_PLUS#####QHD480:480X960, KUANGRE-A17#######
##LCM:
LCM_HEIGHT = 960
LCM_WIDTH = 480
BOOT_LOGO=fwplus
LCD_480_960 = yes
LCD_RESOLUTION = LCM_480_960
CUSTOM_LK_LCM = st7701s_6735_dsi_yk6xx otm8019a_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7701s_6735_dsi_yk6xx otm8019a_6735_dsi_yk6xx

#
##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc2385f_mipi_raw gc5025_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
#CUSTOM_HAL_MAIN2_IMGSENSOR = gc030Amipi_Sensor
CUSTOM_HAL_SUB_IMGSENSOR = gc2385f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc2385f_mipi_raw gc5025_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
#CUSTOM_KERNEL_MAIN2_IMGSENSOR = gc030Amipi_Sensor
CUSTOM_KERNEL_SUB_IMGSENSOR = gc2385f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = icnt7152_tee

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

#A17-E
#CUSTOM_KERNEL_ALSPS = no
#YK_CUSTOM_KERNEL_ALSPS = 
#TOUCHPANEL_TOUCHFELL_IN_PHONE_CALL = yes

#A17-A/E
#American 3m:
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM= yk736_v01_lwg_gsm-quad_wcdma-b2b5_fdd-b2b4b5b7b28


#A17-B
#Europe 4m:
#MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
#MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM= yk736_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b5b7b8b20_tdd-b40

YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

#flash
YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_KUANGRE_A17_FWVGA_PLUS SUB_FLASHLIGHT_SUPPORT HIGH_BATTERY_VOLTAGE_SUPPORT _MAIN2_CAM_SHELTER_DESIGN2_ YK_CAM_SHELTER_SP0A20_MAIN_GC8024 VOLUP_KEY_TO_BACK YK_AC_CHARGER_CURRENT_1150MA
MICROTRUST_TEE_SUPPORT = yes
MTK_TEE_SUPPORT = yes
YKQ_ICNT7152_TEE = yes
#linshi
#BUILD_AGO_GMS = yes
#BUILD_GMS_VERSION = GMS8.1_go_R1
#YK_BOOT_LOGO = kuangre_a17
#HX_SHUT_ANIM = yes
#WW_SHUT_ANIMATION = yes
#WW_SHUT_ANIMATION_TIME = 7

##End of YK736_EMMC_KUANGRE_A17_FWVGA_PLUS#################################

##Start of YK736_EMMC_KUANGRE_A17_HDPLUS#####HD720:720X1440, KUANGRE-A17#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = jd9366_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = jd9366_6735_dsi_yk6xx

#
##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc2385f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc2385f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc2385f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc2385f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = icn7152l

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

#A17-C
#American 3m:
#MTK_MD1_SUPPORT = 14
#MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
#MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM= yk736_v01_lwg_gsm-quad_wcdma-b2b5_fdd-b2b4b5b7b28

#A17-D
#Europe 4m:
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM= yk736_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b5b7b8b20_tdd-b40

YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

#flash
YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_KUANGRE_A17_HDPLUS YK736_CUSTOMER_KUANGRE_A17_FWVGA_PLUS SUB_FLASHLIGHT_SUPPORT HIGH_BATTERY_VOLTAGE_SUPPORT _MAIN2_CAM_SHELTER_DESIGN2_ VOLUP_KEY_TO_BACK YK_CAM_SHELTER_SP0A20_MAIN_GC8024 YK_AC_CHARGER_CURRENT_1150MA

##End of YK736_EMMC_KUANGRE_A17_HDPLUS#################################

##Start of YK736_EMMC_XINJIDE_G1_HDPLUS#####HDPLUS:720X1440, XINJIDE_G1#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = ili9881d_6735_dsi_yk6xx 
CUSTOM_KERNEL_LCM = ili9881d_6735_dsi_yk6xx 

##CAMERA:
CUSTOM_HAL_IMGSENSOR = hi843b_mipi_raw gc5025f_mipi_raw ov8865_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = hi843b_mipi_raw ov8865_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = hi843b_mipi_raw gc5025f_mipi_raw ov8865_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = hi843b_mipi_raw ov8865_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS =fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = GT1X 
TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = microarray
MICROARRY_TEE_SUPPORT = yes
##there are five BB are not dis
##YK_EMMC_CAPACITY=12808
YK_BOARD_CONFIG=YK736_CONFIG YK736_V10_CONFIG
YK_EMMC_CAPACITY=12808_DIS

##MODEM:Europe
#MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
#MTK_PROTOCOL2_RAT_CONFIG = L/W/G
#CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20_tdd-b40

##America
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = L/W/G
CUSTOM_MODEM=yk736_v01_lwg_gsm-quad_wcdma-b1b2b4b5_fdd-b2b4b5b7b12b17_xinjide_ant

YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

YK_CUSTOMER_CONFIG = YK736_CUSTOMER_XINJIDE_G1_HDPLUS EMMC_DISABLE_HS400_SPEED HIGH_BATTERY_VOLTAGE_SUPPORT YK_AC_CHARGER_CURRENT_1150MA VIBRATOR_VOLTAGE_3_0V VOLUP_KEY_TO_BACK PSC5425_CHARGER_SUPPORT YK_CHARGER_CURRENT_BY_LCM

TRUSTKERNEL_TEE_SUPPORT = yes

##End of YK736_EMMC_XINJIDE_G1_HDPLUS#################################

##Start of YK739_EMMC_YKQ_FWVGA#####FWVGA:480X854, YKQ#######
##LCM:
LCM_HEIGHT = 854
LCM_WIDTH = 480
BOOT_LOGO=fwvga
LCD_480_854 = yes
LCD_RESOLUTION = LCM_480_854
CUSTOM_LK_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
# ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
 #ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx

YKQ_FACTORY_SHOW_SUPPORT = yes 

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc2145_mipi_yuv gc2146_mipi_yuv
CUSTOM_HAL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_HAL_SUB_IMGSENSOR = gc2146_mipi_yuv
CUSTOM_KERNEL_IMGSENSOR = gc2145_mipi_yuv gc2146_mipi_yuv
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_KERNEL_SUB_IMGSENSOR = gc2146_mipi_yuv

CUSTOM_HAL_LENS = dummy_lens
CUSTOM_HAL_MAIN_LENS = dummy_lens
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = dummy_lens
CUSTOM_KERNEL_MAIN_LENS = dummy_lens
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = bGT_Hotknot

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = yes
YK_CUSTOM_KERNEL_MAGNETOMETER = st480

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new 

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new 

##fingerprint:
#CUSTOM_KERNEL_FINGERPRINT = cs2511 ft9338
#CUSTOM_KERNEL_FINGERPRINT = ft9338
CUSTOM_KERNEL_FINGERPRINT = cs2511
#CUSTOM_FILES_BRAND = zwl_common

YKQ_USB_OTG_SUPPORT = no

##MODEM:6M
#MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
##CT6M
#CUSTOM_MODEM=
#YK_EMMC_CAPACITY=12808

##MODEM:4M
#MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
#CUSTOM_MODEM=
#YK_EMMC_CAPACITY=6408DDR3

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk739_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20

#YKQ_GPS_CLOCK=yes

#PSC5425_CHARGER_SUPPORT
YK_CUSTOMER_CONFIG = YK739_CUSTOMER_YKQ_FWVGA

YK_CUSTOM_BUILD_VERNO = YKQ_YK739_M11-Y10_GS_ALS_FP_GPSCO_39GO_LWG_6408_20180306_1139

##End of YK739_EMMC_YKQ_FWVGA#################################

##Start of YK739_EMMC_YKQ_HD720#####HD720:720X1280, YKQ#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 720
BOOT_LOGO=hd720
LCD_720_1280 = yes
LCD_RESOLUTION = LCM_720_1280
CUSTOM_LK_LCM = ili9881c_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881c_6735_dsi_yk6xx

MTK_LCM_PHYSICAL_ROTATION_HW=yes

##CAMERA:
CUSTOM_HAL_IMGSENSOR = ov8825_mipi_raw gc8024f_mipi_raw gc5025f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = ov8825_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw gc8024f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = ov8825_mipi_raw gc8024f_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = ov8825_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw gc8024f_mipi_raw

CUSTOM_HAL_LENS = dummy_lens
CUSTOM_HAL_MAIN_LENS = dummy_lens
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = dummy_lens
CUSTOM_KERNEL_MAIN_LENS = dummy_lens
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = msg2xxx_v3a00
#TOUCHPANEL_GESTURE = yes

##magnetometer
#CUSTOM_KERNEL_MAGNETOMETER = no
#YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
#CUSTOM_KERNEL_ACCELEROMETER = yes
#YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
#CUSTOM_KERNEL_GYROSCOPE = no
#YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

##MODEM:6M
MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
MTK_PROTOCOL2_RAT_CONFIG = L/W/G
#CUSTOM_MODEM=yk739_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
#CUSTOM_MODEM=yk739_v01_lwctg_gsm-triple_wcdma-b1b8_fdd-b1b3b5_tdd-b38b39b40b41_tds-b34b39_evdo-bc0
#CUSTOM_MODEM=yk739_v01_lwctg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20_tdd-b38_tds-b34b39_evdo-bc0
CUSTOM_MODEM=yk739_v01_lwctg_gsm-quad_wcdma-b1b2b5b8_fdd-b1b2b3b5b7b8b17b20_tdd-b38b39b40b41_tds-b34b39_evdo-bc0

##MODEM:3M
#MTK_MD1_SUPPORT = 14
#MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
#MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk739_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20

#6408
YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK739_CUSTOMER_YKQ_HD720

##End of YK739_EMMC_YKQ_HD720#################################


##Start of YK739_EMMC_CHANGSHENGTAI_H209_HDPLUS#####HDPLUS:720X1440, CHANGSHENGTAI-H209#######
##LCM:
LCM_HEIGHT = 1440
LCM_WIDTH = 720
BOOT_LOGO=hdplus
LCD_720_1440 = yes
LCD_RESOLUTION = LCM_720_1440
CUSTOM_LK_LCM = st7703_6735_dsi_yk6xx ili9881d_6735_dsi_yk6xx  jd9365_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7703_6735_dsi_yk6xx ili9881d_6735_dsi_yk6xx jd9365_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = s5k3l8_mipi_raw ov8865_mipi_raw gc5025f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = s5k3l8_mipi_raw ov8865_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = s5k3l8_mipi_raw ov8865_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = s5k3l8_mipi_raw ov8865_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dw9714af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af dw9714af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dw9714af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af dw9714af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL =lu2x3a1 icn87xx GT1X
#TOUCHPANEL_GESTURE = yes

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

CUSTOM_KERNEL_FINGERPRINT = cs2511

YKQ_USB_OTG_SUPPORT=yes

CUSTOM_KERNEL_MAGNETOMETER = yes
YK_CUSTOM_KERNEL_MAGNETOMETER = st480
CUSTOM_KERNEL_ORIENTATION_SENSOR = yes

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk739_v01_lwg_gsm-quad_wcdma-b1b8_fdd-b1b3b7b8b20

#6408
#YK_EMMC_CAPACITY=6408DDR3
YK_EMMC_CAPACITY=12816

YKQ_POWERKEY_LONGPRESS_SHUTDOWN=2

#CAMERA_USE_CHAOQUN_TURNING
YK_CUSTOMER_CONFIG = YK739_CUSTOMER_CHANGSHENGTAI_H209_HDPLUS GT1X_FORCE_I2C_ADDRESS HIGH_BATTERY_4_4_V _MAIN2_CAM_SHELTER_DESIGN2_ YK_CAM_SHELTER_SP0A20_MAIN_GC8024 YK_AC_CHARGER_CURRENT_1350MA  VOLUP_KEY_TO_BACK CAMERA_USE_CHAOQUN_TURNING

#YK_CUSTOMER_CONFIG = YK739_CUSTOMER_CHANGSHENGTAI_H209_HDPLUS GT1X_FORCE_I2C_ADDRESS HIGH_BATTERY_4_4_V _MAIN2_CAM_SHELTER_DESIGN2_ YK_CAM_SHELTER_SP0A20_MAIN_GC8024 YK_AC_CHARGER_CURRENT_1350MA  VOLUP_KEY_TO_BACK 
#YK_BOOT_LOGO = changshengtai_h209

##End of YK739_EMMC_CHANGSHENGTAI_H209_HDPLUS#################################


##Start of YK568_EMMC_YKQ_HD720#####HD720:720X1280, YKQ#######
##LCM:
LCM_HEIGHT = 1280
LCM_WIDTH = 720
BOOT_LOGO=hd720
LCD_720_1280 = yes
LCD_RESOLUTION = LCM_720_1280
CUSTOM_LK_LCM = ili9881c_6735_dsi_yk6xx st7703_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = ili9881c_6735_dsi_yk6xx st7703_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = ov8856_mipi_raw hi556f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = ov8856_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = hi556f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = ov8856_mipi_raw hi556f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = ov8856_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = hi556f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = gslX680
#TOUCHPANEL_GESTURE = yes

##modem 5m:
MTK_MD1_SUPPORT = 10
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/T/G
MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk568_v01_lwctg_gsm-quad_wcdma-b1b2b5b8_fdd-b1b2b3b4b5b7b8b12b17b20b28_tdd-b38b39b40b41_tds-b34b39
CUSTOM_MODEM=yk568_v01_lwctg_gsm-quad_wcdma-b1b2b3b5b8_fdd-b1b2b3b4b5b7b8b12b17b20b28_tdd-b38b39b40b41_tds-b34b39_b2b3-switch

##Dual-Mic:
MTK_DUAL_MIC_SUPPORT=yes
MTK_INCALL_NORMAL_DMNR=yes

#12808
YK_EMMC_CAPACITY=12808

YK_CUSTOMER_CONFIG = YK568_CUSTOMER_YKQ_HD720

##End of YK568_EMMC_YKQ_HD720#################################


##Start of YK568_EMMC_SHUANGHOU_WVGA#####WVGA:480X800, SHUANGHOU#######
##LCM:
LCM_HEIGHT = 800
LCM_WIDTH = 480
BOOT_LOGO=wvga
LCD_480_800 = yes
LCD_RESOLUTION = LCM_480_800
CUSTOM_LK_LCM = hx8379a_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = hx8379a_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = ov8856_mipi_raw hi556f_mipi_raw gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = ov8856_mipi_raw gc8024_mipi_raw hi846_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = hi556f_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = ov8856_mipi_raw hi556f_mipi_raw gc8024_mipi_raw gc5025f_mipi_raw hi846_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = ov8856_mipi_raw gc8024_mipi_raw hi846_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = hi556f_mipi_raw gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = hx852xes
#TOUCHPANEL_GESTURE = yes

##Breath LED:
YKQ_BREATH_LED_SUPPORT = aw2013

##modem 5m:
MTK_MD1_SUPPORT = 10
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/T/G
MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk568_v01_lwctg_gsm-quad_wcdma-b1b2b5b8_fdd-b1b2b3b4b5b7b8b12b17b20b28_tdd-b38b39b40b41_tds-b34b39
CUSTOM_MODEM=yk568_v01_lwctg_gsm-quad_wcdma-b1b2b5b8_fdd-b1b2b3b4b5b7b8b12b17b20b28_tdd-b38b39b40b41_tds-b34b39_ant

#12808
YK_EMMC_CAPACITY=12808

YK_CUSTOMER_CONFIG = YK568_CUSTOMER_SHUANGHOU_WVGA

##End of YK568_EMMC_SHUANGHOU_WVGA################################


##Start of YK737_EMMC_YKQ_FWVGA#####FWVGA:480X854, YKQ#######
##LCM:
LCM_HEIGHT = 854
LCM_WIDTH = 480
BOOT_LOGO=fwvga
LCD_480_854 = yes
LCD_RESOLUTION = LCM_480_854
CUSTOM_LK_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
# ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = lcd_ata_test ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx st7701s_6735_dsi_yk6xx
 #ili9806e_6735_dsi_yk6xx st7701_6735_dsi_yk6xx

YKQ_FACTORY_SHOW_SUPPORT = yes 

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc2145_mipi_yuv gc0310_mipi_yuv
CUSTOM_HAL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_HAL_SUB_IMGSENSOR = gc0310_mipi_yuv
CUSTOM_KERNEL_IMGSENSOR = gc2145_mipi_yuv gc0310_mipi_yuv
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc2145_mipi_yuv
CUSTOM_KERNEL_SUB_IMGSENSOR = gc0310_mipi_yuv

CUSTOM_HAL_LENS = dummy_lens
CUSTOM_HAL_MAIN_LENS = dummy_lens
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = dummy_lens
CUSTOM_KERNEL_MAIN_LENS = dummy_lens
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = bGT_Hotknot

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER = 

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new 

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new 

##fingerprint:
#CUSTOM_KERNEL_FINGERPRINT = cs2511 ft9338
#CUSTOM_KERNEL_FINGERPRINT = ft9338
#CUSTOM_KERNEL_FINGERPRINT = icn7152l
#CUSTOM_FILES_BRAND = zwl_common

YKQ_USB_OTG_SUPPORT = no

##MODEM:6M
#MTK_PROTOCOL1_RAT_CONFIG = C/Lf/Lt/W/T/G
##CT6M
#CUSTOM_MODEM=
#YK_EMMC_CAPACITY=12808

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
CUSTOM_MODEM=yk737_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40
YK_EMMC_CAPACITY=6408DDR3

##MODEM:3M
#MTK_MD1_SUPPORT = 14
#MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
#CUSTOM_MODEM=
#YK_EMMC_CAPACITY=12808

YKQ_GPS_CLOCK=yes

#PSC5425_CHARGER_SUPPORT
YK_CUSTOMER_CONFIG = YK737_CUSTOMER_YKQ_FWVGA

YK_CUSTOM_BUILD_VERNO = YKQ_YK737_M01-Y10_GS_ALS_FP_GPS_39GO_LWG_6408_20180306_1139

##End of YK737_EMMC_YKQ_FWVGA#################################


##Start of YK737_EMMC_CAIFU9_KS972A_FWPLUS#####FWPLUS:480X960, CAIFU9-KS972A#######
##LCM:
LCM_HEIGHT = 960
LCM_WIDTH = 480
BOOT_LOGO=fwplus
LCD_480_960 = yes
LCD_RESOLUTION = LCM_480_960
CUSTOM_LK_LCM = st7701s_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7701s_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

#CUSTOM_KERNEL_FINGERPRINT = cs2511

#YKQ_USB_OTG_SUPPORT=yes

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:4M
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
CUSTOM_MODEM=yk737_v01_lwg_gsm-quad_wcdma-b1b2b8_fdd-b1b3b5b7b8b20_tdd-b38b40

YKQ_GPS_CLOCK=yes

YK_EMMC_CAPACITY=6408DDR3
YK_EMMC_CAPACITY=12816

YK_CUSTOMER_CONFIG = YK737_CUSTOMER_CAIFU9_KS972_FWPLUS HIGH_BATTERY_VOLTAGE_SUPPORT VOLUP_KEY_TO_BACK

##End of YK737_EMMC_CAIFU9_KS972A_FWPLUS#################################


##Start of YK737_EMMC_CAIFU9_KS972B_FWPLUS#####FWPLUS:480X960, CAIFU9-KS972B#######
##LCM:
LCM_HEIGHT = 960
LCM_WIDTH = 480
BOOT_LOGO=fwplus
LCD_480_960 = yes
LCD_RESOLUTION = LCM_480_960
CUSTOM_LK_LCM = st7701s_6735_dsi_yk6xx
CUSTOM_KERNEL_LCM = st7701s_6735_dsi_yk6xx

##CAMERA:
CUSTOM_HAL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_HAL_SUB_IMGSENSOR = gc5025f_mipi_raw
CUSTOM_KERNEL_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw gc5025f_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = gc8024_mipi_raw gc5025_mipi_raw
CUSTOM_KERNEL_SUB_IMGSENSOR = gc5025f_mipi_raw

CUSTOM_HAL_LENS = fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS = fm50af
CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_KERNEL_LENS = fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS = fm50af
CUSTOM_KERNEL_SUB_LENS = dummy_lens

##TouchPanel
CUSTOM_KERNEL_TOUCHPANEL = ft6x36
#TOUCHPANEL_GESTURE = yes

##magnetometer
CUSTOM_KERNEL_MAGNETOMETER = no
YK_CUSTOM_KERNEL_MAGNETOMETER =

##accelerometer:
CUSTOM_KERNEL_ACCELEROMETER = yes
YK_CUSTOM_KERNEL_ACCELEROMETER = mc3410_new

##gyroscope:
CUSTOM_KERNEL_GYROSCOPE = no
YK_CUSTOM_KERNEL_GYROSCOPE = 

YK_CUSTOM_KERNEL_ALSPS = stk3x1x_new

MTK_FULLSCREEN_SWITCH_SUPPORT = yes

##MODEM:3M
MTK_MD1_SUPPORT = 14
MTK_PROTOCOL1_RAT_CONFIG = Lf/W/G
MTK_PROTOCOL2_RAT_CONFIG = G
#CUSTOM_MODEM=yk737_v01_lwg_gsm-dual850_wcdma-b1b2b4b5_fdd-b1b2b4b5b7b12b28
CUSTOM_MODEM=yk737_v01_lwg_gsm-dual850_wcdma-b1b2b4b5_fdd-b1b2b4b5b7b12b28_caifu9_ant

YKQ_GPS_CLOCK=yes

YK_EMMC_CAPACITY=6408DDR3

YK_CUSTOMER_CONFIG = YK737_CUSTOMER_CAIFU9_KS972_FWPLUS HIGH_BATTERY_VOLTAGE_SUPPORT VOLUP_KEY_TO_BACK

##End of YK737_EMMC_CAIFU9_KS972B_FWPLUS#################################

